### ISSUE TITLE
Planet eStream is permanently DISABLED in Moodle

### ISSUE THREAD

**Issue by Fae6068123** [PlaneteStream/moodle-filter_planetestream#2]
when attempting to install planet e-stream it is appearing as disabled. this is incorrect. 

![image](https://user-images.githubusercontent.com/59917516/123095959-83cc9280-d426-11eb-9ce3-1e8e82be601b.png)

**Comment by Fae6068123** [comment]
There is no settings to enable. I expect this is a known issue.

**Comment by PlaneteStream** [comment]
Hi @Fae6068123,

You have to turn the filter on by going to Site Administration > Plugins > Manage Filters.
